name: SwiftUI ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Lint Code
        uses: cirruslabs/swiftlint-action@v1
        with:
          version: 'latest'
        continue-on-error: false
        
      - name: Build and test
        env:
          scheme: "koliko+"
          platform: "platform=iOS Simulator,name=iPhone 15,OS=17.2"
        run: |
            set -o pipefail
            SIMULATOR_ID=$(xcrun simctl list devices available | grep iPhone | head -1 | grep -E -o '[0-9A-F-]{36}')
            xcodebuild test \
              -scheme "$scheme" \
              -destination "platform=iOS Simulator,id=$SIMULATOR_ID" \
              -enableCodeCoverage YES \
              CODE_SIGNING_ALLOWED=NO | xcpretty
