name: SwiftUI ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Lint Code
        uses: cirruslabs/swiftlint-action@v1
        with:
          version: 'latest'
        continue-on-error: false
        
      - name: Build and test
        env:
          scheme: "AppScheme"
          platform: "platform=iOS Simulator,name=iPhone 15,OS=latest"
        run: |
          set -o pipefail
          xcodebuild test \
            -scheme "$scheme" \
            -destination "$platform" \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO | xcpretty
